### ISSUE TITLE
Code examples : add syntax highlighting

### ISSUE THREAD

**Issue by RadhikaKaul** [worldbank/dime-data-handbook#103]
From Leo:
https://github.com/worldbank/d4di/blob/e7d1b125c814ff7a69464ce247980b59b2bf0287/chapters/introduction.tex#L135

**Comment by bbdaniels** [comment]
?

**Comment by kbjarkefur** [comment]
I guess it means syntax highlighting. I spent a fair bit of time trying to do this last year. I can do again after we have submitted to professional review

**Comment by bbdaniels** [comment]
https://github.com/mcaceresb/highlight-sas-stata

**Comment by luizaandrade** [comment]
Shall we label this "won't fix"?

**Comment by kbjarkefur** [comment]
I was thinking of fiddling with this when everything else is done

**Comment by kbjarkefur** [comment]
See if we can at least have comments one color and code one color

**Comment by luizaandrade** [comment]
this works now on markdown :)
