### ISSUE TITLE
Ch 2: link to markdown resources?

### ISSUE THREAD

**Issue by luizaandrade** [worldbank/dime-data-handbook#176]
Either expand what's in there, or just link to a more detailed discussion (maybe in the wiki?)

**Comment by kbjarkefur** [comment]
What part of the latex file is this a reference to? anyone that remembers?

**Comment by bbdaniels** [comment]
https://github.com/worldbank/d4di/blob/a39045809799d6eed48b5266d727b5a08fa308d2/chapters/planning-data-work.tex#L385

Added a little explanation in my review. The authoritative resource written by the original developer is https://daringfireball.net/projects/markdown/ or https://daringfireball.net/projects/markdown/syntax if we want to add one of those as a link.

**Comment by luizaandrade** [comment]
I think this is good now. Close?
