### ISSUE TITLE
Ch2: Example do-file

### ISSUE THREAD

**Issue by mariaruth** [worldbank/dime-data-handbook#188]
The master do file is helpful, and we should refer back to it more in the text to add clarity. To give one example, when we discuss creating global macros, refer the reader to lines 36-40 of the do file so they can see exactly what this means. There are lots of other examples throughout.

**Comment by luizaandrade** [comment]
link to this as we read the book agiain

**Comment by mariaruth** [comment]
I added specific references here:

a lot of the coding recommendations we make aren't applicable to a master .do file, but would benefit from examples. might consider another example .do file. for example, record inputs / outputs, comments (what and why), modular code. but this is low priority.

**Comment by mariaruth** [comment]
Part 1 does not actually do what is referenced here. should add that to the .do file. 

https://github.com/worldbank/d4di/blob/8b98e52c899291a674ce23ea3174fdc4d349126d/chapters/planning-data-work.tex#L563

**Comment by kbjarkefur** [comment]
Add section switches to the clean do files etc.

**Comment by luizaandrade** [comment]
I think this can be clsoed, right?
