### ISSUE TITLE
Ch 2: file name conventions

### ISSUE THREAD

**Issue by mariaruth** [worldbank/dime-data-handbook#190]
i think it would be useful to have a wiki page on naming conventions, that we could link to here, and reduce the amount of detail (e.g. the point about forward vs back slashes). 

Re: naming conventions, add 'why' (i.e. why not use spaces in names of technical files). add other conventions, such as do not use your own name, or a date. possibly a note to be wary of extremely long file paths.

**Comment by kbjarkefur** [comment]
@bbdaniels you assigned me and added a wiki label? does that mean that you want me to write it? Did you do updates to the book in regards to this issue?

**Comment by bbdaniels** [comment]
Do we need this in the book or should this be wiki-only? We link a resource: http://www2.stat.duke.edu/~rcs46/lectures_2015/01-markdown-git/slides/naming-slides/naming-slides.pdf

So I am willing to close at this stage since we don't have any more specific recommendations at this time

**Comment by luizaandrade** [comment]
I think the book already discusses this a lot. but we can add a wiki page to the wishlist.

**Comment by mariaruth** [comment]
Point in the original issue was to remove some of the content currently in the book to a wiki page; it seems like a level of detail better suited to the Wiki

**Comment by mariaruth** [comment]
Specifically, i think we should remove the content quoted below to a wiki page and add a wiki link here. i went ahead with this here f59a7227788defa9553509c5fcd4852020b9b75b and made a pull request (#394).

https://github.com/worldbank/d4di/blob/8b98e52c899291a674ce23ea3174fdc4d349126d/chapters/planning-data-work.tex#L452

> Some of the differences between the two naming approaches are major and may be new to you,
so below are a few examples. Introducing spaces between words in a file name (including the folder path) can break a file's path when it's read by code, so while a Word document may be called \texttt{2019-10-30 Sampling Procedure Description.docx}, a related do file would have a name like \texttt{sampling-endline.do}. Adding timestamps to binary files as in the example above can be useful, as it is not straightforward to track changes using version control software. However, for plaintext files version-controlled using Git, timestamps are an unnecessary distraction. Similarly, code-compatiable files should never include capital letters, as strings and file paths are case-sensitive in some software. Finally, one organizational practice that takes some getting used to
is the fact that the best names from a coding perspective are usually the opposite of those from an English perspective. For example, for a deidentified household dataset from the baseline round,
you should prefer a name like \texttt{baseline-household-deidentified.dta}, rather than the opposite way around as occurs in natural language. This ensures that all \texttt{baseline} data stays together,
then all \texttt{baseline-household} data, and finally provides unique information about this specific file.

**Comment by bbdaniels** [comment]
Wiki page is created, needs content, redundant to #438
