### ISSUE TITLE
Ch 7: Add code review documents

### ISSUE THREAD

**Issue by escandethomas** [worldbank/dime-data-handbook#209]
https://github.com/worldbank/d4di/blob/a9c4d76da0787053a59fee0c928001e04df648bc/chapters/publication.tex#L157

As it is now mandatory in DIME, I would add here a reminder that one should probably also release the proof that code review was done and the main comments and answer somewhere.

**Comment by luizaandrade** [comment]
I'll add link to the code review checklists and to a filled one in a replication package

**Comment by bbdaniels** [comment]
Should we do this via wiki? Tagged as such

**Comment by mariaruth** [comment]
I think it could be good to add the checklist link to the main text. let's discuss.

**Comment by bbdaniels** [comment]
Linked DIME Standards now, closing, but all those links need review in #499
