### ISSUE TITLE
Ch4: power calcs by simulation

### ISSUE THREAD

**Issue by mariaruth** [worldbank/dime-data-handbook#247]
> We suggest doing all power calculations by simulation

Do we?

I'm not sure I agree. I think simulation is best practice, but `power` and `clustersampsi` can do a lot and are commonly used. At the least, we need to add more motivation here for why to do power calcs by simulation - and perhaps a taxonomy for when inbuilt commands suffice. 

> but they will not answer most of the practical questions that complex experimental designs require 

this raises the questions of what they cannot answer and for what designs they would be appropriate. 

> If you are willing to make even more assumptions, you can use one of the built-in functions

be explicit about what assumptions

**Comment by mariaruth** [comment]
Also, if we do agree to recommend doing all power calcs with simulations, should significantly update the linked wiki page. Currently nothing on the wiki about simulation.

**Comment by luizaandrade** [comment]
I vote for:
- Recommend using simulation
- Discuss pros and cons
- Show examples of both

**Comment by kbjarkefur** [comment]
We agreed to what Luiza is voting for. But do not have the examples in the book.

**Comment by kbjarkefur** [comment]
I think what we currently have in the book reflects the sentiments expressed in this thread. So I vote for close, but @bbdaniels you probably know best if this is the case

**Comment by mariaruth** [comment]
wiki needs significant updating on this, so i vote to leave open with wiki tag

**Comment by bbdaniels** [comment]
Redundant to #438
