### ISSUE TITLE
Ch 6 : include discussion on weights

### ISSUE THREAD

**Issue by luizaandrade** [worldbank/dime-data-handbook#251]

**Comment by luizaandrade** [comment]
Do we still want to add this? I don't think it fits into the chapter as it reads now, and I also can't remember in what context I opened this issue.

**Comment by bbdaniels** [comment]
leave it open for final review, it might warrant a small mention. we should at least have a wiki page for it and a link

**Comment by bbdaniels** [comment]
Closing redundant to #438
