### ISSUE TITLE
Ch5: diagram?

### ISSUE THREAD

**Issue by mariaruth** [worldbank/dime-data-handbook#259]
i think it would be helpful to have a diagram showing the progression between the various steps here -- questionnaire design, programming, data collection in field, data submitted to cloud( encryption in transit), data on server (encryption at rest), data download branching into the multiple locations. i don't know exactly what it would look like, but i think it would help the narrative structure here for all readers to see clearly how it fits together.

**Comment by mariaruth** [comment]
suggest moving section of fieldwork/quality assurance to before section on collecting data securely. i think the encryption stuff is useful but it gets a bit in the weeds and it's not the content i would immediately look for based on the chapter title/intro.

**Comment by mariaruth** [comment]
![image](https://user-images.githubusercontent.com/23041354/67977093-c2785e00-fbed-11e9-9ded-6f2dba07218d.png)

**Comment by kbjarkefur** [comment]
First reorder and re-write the chapter, and then come back to this issue and see if we still want this.

**Comment by mariaruth** [comment]
If we do add diagrams to this chapter, should think about adding them to other chapters as well

**Comment by bbdaniels** [comment]
Vote to close. No diagrams at this time.

**Comment by luizaandrade** [comment]
we agreed to not add diagrams in the book, but keep them in the wiki. I think we leave this open with a wiki tag

**Comment by bbdaniels** [comment]
Closing this since the diagrams are under way
