### ISSUE TITLE
Stata style guide: use `=` to define globals

### ISSUE THREAD

**Issue by luizaandrade** [worldbank/dime-data-handbook#380]
> All macros should be defined using the \texttt{=} operator.

*Luiza:* I think we should discuss this.

*Kris:* Agreed that this should not be our recommendation. When the `=` operator is used long strings are truncated. So unless you know your strings are short then ```local mystr "`str1' `str2'"``` should always be preferred to ```local mystr = "`str1'" + "`str2'"```

*Ben:* I didn't know that. At what length does this happen? I generally use:
```
local mystr = "`str1' `str2'"
```

**Comment by bbdaniels** [comment]
👍🏼

**Comment by kbjarkefur** [comment]
done in #509
