### ISSUE TITLE
Stata style guide: When to use `qui`

### ISSUE THREAD

**Issue by luizaandrade** [worldbank/dime-data-handbook#381]
> This can be accomplished by using \texttt{run file.do} rather than \texttt{do file.do}.
> Run outputs like \texttt{reg} using the \texttt{qui} prefix.
> Never use interactive commands like \texttt{sum} or \texttt{tab} in dofiles,
> unless they are combined with \texttt{qui} for the purpose of getting \texttt{r()}-statistics.

Why `qui`? I can agree that is a good preference, but I do not see a reason to say that you cannot use `sum` and `tab` unless combined with `qui`

_Originally posted by @kbjarkefur in https://github.com/_render_node/MDExOlB1bGxSZXF1ZXN0MzUzMjMwOTA1/timeline/more_items_

**Comment by luizaandrade** [comment]
We discussed that a longer discussion should be included about what to print or not, and that `tab`, `sum` and `reg` outputs should be stored to a file rather than printed.

**Comment by bbdaniels** [comment]
I think this is done by https://github.com/worldbank/d4di/pull/382/commits/551d748fcf631fd2e297265ecfd4bf1109797591

**Comment by bbdaniels** [comment]
Revised slightly in https://github.com/worldbank/d4di/pull/382/commits/551d748fcf631fd2e297265ecfd4bf1109797591. Could include more detail in revision.

**Comment by luizaandrade** [comment]
A bit late for me to realize this, but I think that's a link to the wrong commit

**Comment by kbjarkefur** [comment]
I think we can close this. I do not think this is important enough to make the cut
