### ISSUE TITLE
Final review - 'original' data instead of 'primary' data

### ISSUE THREAD

**Issue by mariaruth** [worldbank/dime-data-handbook#387]
@bbdaniels suggested 'original data' in chapter 1 edits, i think this is the right wording to go with throughout the book (rather than 'primary' or 'raw'). it's inclusive of all data types, and gives the right emphasis on data that's being used for the first time for the purpose at hand.

**Comment by kbjarkefur** [comment]
I agree with the overall point. 

However, don't we sometimes make point specific to primary data where we should use that word specifically? This does not contradict your point, just saying it has to be done more intelligently than a _replace all_.

Second however. I think 'orginal data' can replace both 'primary data' and 'raw data', but maybe not both at the same time, as I think there is an important difference between 'primary' and 'raw'. Primary is a type of data, and raw describes a function a data set has in a specific project.

**Comment by luizaandrade** [comment]
done in 8c85c31

**Comment by luizaandrade** [comment]
done in 8c85c31

**Comment by luizaandrade** [comment]
duplicates with #415, closing #415
