### ISSUE TITLE
Links to external resources

### ISSUE THREAD

**Issue by mariaruth** [worldbank/dime-data-handbook#389]
This is something to think about after the next round of review {not urgent}.

As we improve the wiki pages, those should always have links to external resources. Given that, i wonder how much it makes sense to include those cites directly in the book, vs. pointing them to the wiki. 

in some cases we use external resources for a very specific point. perhaps then it makes sense to keep. but often it's just things that are broadly related to the section at hand.

**Comment by bbdaniels** [comment]
Had this discussion today with Maria & Avnish: general goal will be to remove all these to the Wiki. Ideally almost all links in the book will be to Wiki (or at least to wb.org addresses to include blogposts), although this will take some work.

**Comment by luizaandrade** [comment]
Duplicated with #428
