### ISSUE TITLE
Data set -> dataset

### ISSUE THREAD

**Issue by luizaandrade** [worldbank/dime-data-handbook#413]
https://github.com/worldbank/d4di/blob/f0f6ed8d22441f04e38fb0d6e335df45540bbceb/chapters/data-analysis.tex#L491

https://github.com/worldbank/d4di/blob/f0f6ed8d22441f04e38fb0d6e335df45540bbceb/chapters/data-analysis.tex#L497

**Comment by kbjarkefur** [comment]
Organize all of these type of final review into one issue
