### ISSUE TITLE
Appendix with condensed time line:

### ISSUE THREAD

**Issue by kbjarkefur** [worldbank/dime-data-handbook#417]
From @ypowers1:

> [...] it's clear many topics overlap and are mentioned in several different chapters, e.g. de-identification. It got a bit confusing at times trying to remember when in the process I needed to ideally have done a specific task or implement a specific action (like creating the best practice folders). I realize this would be adding more work, but it might be helpful to create an "ideal" project timeline/checklist that lists out all the things you should be thinking about in each step of the data process? Just brainstorming - this might be unrealistic given how complicated some of the tasks are, but something highly stylized/simplified could be a helpful resource.

**Comment by kbjarkefur** [comment]
My reply:

> [...] We tried to mention it only where you had to, in one way or another, think about it and include it when you plan your data work. But based on your feedback I see that there is difference between that and when you need to take a specific action. 

> Using the de-identification example. During the planning of your work (chapter 1) you need to think about which data sets will be identified so that you know. Then in you need to set up your file structure to accomodate that (chapter 2) and then you need to do the actually de-identification before you start cleaning the data (chapter 6). And then you need to do a publication de-identification before publishing the data (chapter 7)

A timeline in an appendix (or something) where you can see where each action is, and thereby also see how they slightly differ is not a bad idea

**Comment by mariaruth** [comment]
i think this would be useful!

**Comment by kbjarkefur** [comment]
See how much this overlaps with the overview diagram that we are already preparing
