### ISSUE TITLE
List of concepts in the book that need a definition

### ISSUE THREAD

**Issue by luizaandrade** [worldbank/dime-data-handbook#420]
Concepts used in each chapter:

## Chapter 1A
- [ ] Reproducibility
- [ ] Transparency
- [ ] Credibility
- [ ] Computational reproducibility
- [ ] Master script
- [ ] Pre-registration
- [ ] Pre-analysis plan
- [ ] Registered reports
- [ ] File-drawer problem

## Chapter 1B
- [ ] PII
- [ ] Data ownership
- [ ] "Confidential data"
- [ ] IRB
- [ ] Encryption
- [ ] Human subjects
- [ ] De-identification
- [ ] Anonymization
- [ ] Risk of disclosure

**Comment by luizaandrade** [comment]
## Chapter 2
- [ ] Plaintext files

## Chapter 4
- [ ] Pseudocode

**Comment by kbjarkefur** [comment]
I closed this an moved this to one issues for all final review items #476

**Comment by kbjarkefur** [comment]
I see you updated there as well. Great! leaving these comments here so future us knows
