### ISSUE TITLE
Create "Impact evaluation methods Wiki page" based on Appendix

### ISSUE THREAD

**Issue by luizaandrade** [worldbank/dime-data-handbook#422]
Arianna suggested moving it to chapter 6. Another possible option is to make it an appendix

**Comment by kbjarkefur** [comment]
Make this appendix and wiki page.

**Comment by kbjarkefur** [comment]
Make an "IE methods that everyone should know" wiki page that duplicates this appendix. It is so well written so that it can be both a wiki page and the appendix

**Comment by kbjarkefur** [comment]
It was made into an appendix
