### ISSUE TITLE
Intro: address Arianna's comments

### ISSUE THREAD

**Issue by luizaandrade** [worldbank/dime-data-handbook#424]
Edit the intro to address the following points:
- [x] My other general comment is that this is four author guide that gives no credit to the work of everybody who contributed to DIME and DIME Analytics. I am worried about this. The background should be DIME and why we established DIME Analytics and what DIME Analytics produced as a result of working on DIME projects.
- [x] The introduction should have a clear motivation of why data and not only research design is important for generating credible evidence. Here you need to make reference to actual research on the perils of poor data on research conclusions. 
- [x] It will have to explain what DIME does (either without copying and pasting or by using quotes and referring to the original documents). You need to include stats on the size of our data efforts, the size of our FC and RA pools, and how this motivated the establishment of DIME analytics and how DIME analytics capitalized on the knowledge generated in the process of doing research  and field work. 
- [x] The intro should also give an overview of the transformation in expectations from the development economics profession and how this created a different institutional framework for us to work in and contribute to. Separating what was done by others e.g. registries, and what our contribution has been, e.g. proper protocols for reproducibility, is very important. None of our contribution comes out.
- [x] Somewhere we should also explain all the efforts you undertake on the issue of continuing education. Things are moving fast and so are we. Do explain what we do and what public good service we offer as a result. (link to appendix on resources)
- [x] Make it clear on the intro that the book follows the steps of a project cycle

**Comment by kbjarkefur** [comment]
Cross with #481

**Comment by kbjarkefur** [comment]
Assigned maria as she is assigned to #481

**Comment by kbjarkefur** [comment]
Can this be closed now?
