### ISSUE TITLE
Split chapter 1

### ISSUE THREAD

**Issue by luizaandrade** [worldbank/dime-data-handbook#425]
Split chapter 1 into two chapters:

### Chapter 1 is on Reproducibility:
Chapter 1 should be retitled to Protocols for Reproducibility and focus squarely on reproducibility, transparency and credibility (part one of that chapter and please make sure to define all the concepts); it should then explain how we operationalize the concepts into protocols for all of our projects and what those protocols are. It should discuss barriers to adoption and why academic institutions should adopt ways to support researchers at scale. Part two of that chapter does not belong in the same chapter. Include examples.

### Chapter 2 is on Data Security:
A new Chapter 2 can then handle the issues of safety (part two of current chapter 1). Since we just wrote a chapter for the IDEA handbook, let’s make sure we draw and reference from it. That chapter incorporates DIME examples throughout. The issues of safety are covered again to similar length in later parts of the book. Let’s make sure not to repeat.
- [ ] all the content about de-identification will be moved there, with references to this chapter when we talk about data cleaning and publication

**Comment by bbdaniels** [comment]
I can handle the first part of this for the new Chapter 1.
