### ISSUE TITLE
Remove all non-DIME-controlled links from book

### ISSUE THREAD

**Issue by bbdaniels** [worldbank/dime-data-handbook#428]
URLs that are allowed in book:

- DIME wiki
- Any worldbank.org link (including blogs, docs, etc.)
- Links to _top-level domain_ of specific sites or services referenced

Everything else should be moved to Wiki, defined in sidenote, or cited as an academic reference.

**Comment by Avnish95** [comment]
### List of links that need to migrate to Wiki ( and suggested Wiki pages )

**Comment by Avnish95** [comment]
https://github.com/worldbank/dime-data-handbook/blob/f8afdcbe047cc41bd29302cc098a0f7b6614ec83/chapters/0-introduction.tex#L340

https://dimewiki.worldbank.org/wiki/Software_Tools#Statistical_Software

**Comment by Avnish95** [comment]
https://github.com/worldbank/dime-data-handbook/blob/f8afdcbe047cc41bd29302cc098a0f7b6614ec83/chapters/1-reproducibility.tex#L332

https://dimewiki.worldbank.org/wiki/Reproducible_Research

**Comment by Avnish95** [comment]
https://github.com/worldbank/dime-data-handbook/blob/f8afdcbe047cc41bd29302cc098a0f7b6614ec83/chapters/1-reproducibility.tex#L389

https://dimewiki.worldbank.org/wiki/Reproducible_Research#Replication_and_Reproducibilty 
(Can add more on replicability from the URL originally referenced)

**Comment by Avnish95** [comment]
https://github.com/worldbank/dime-data-handbook/blob/f8afdcbe047cc41bd29302cc098a0f7b6614ec83/chapters/2-collaboration.tex#L78

https://dimewiki.worldbank.org/wiki/Data_Security (Need to add 3-2-1 Backup Strategy on this, align with DIME Data Security Standards)

**Comment by Avnish95** [comment]
https://github.com/worldbank/dime-data-handbook/blob/f8afdcbe047cc41bd29302cc098a0f7b6614ec83/chapters/2-collaboration.tex#L564

https://dimewiki.worldbank.org/wiki/Protecting_Human_Research_Subjects#United_States_Standards (Add information)

**Comment by Avnish95** [comment]
https://github.com/worldbank/dime-data-handbook/blob/f8afdcbe047cc41bd29302cc098a0f7b6614ec83/chapters/2-collaboration.tex#L567

https://dimewiki.worldbank.org/wiki/Protecting_Human_Research_Subjects#European_Standards (Add information)

**Comment by Avnish95** [comment]
https://github.com/worldbank/dime-data-handbook/blob/f8afdcbe047cc41bd29302cc098a0f7b6614ec83/chapters/2-collaboration.tex#L564

https://dimewiki.worldbank.org/wiki/Protecting_Human_Research_Subjects#United_States_Standards

**Comment by Avnish95** [comment]
https://github.com/worldbank/dime-data-handbook/blob/f8afdcbe047cc41bd29302cc098a0f7b6614ec83/chapters/2-collaboration.tex#L78

https://dimewiki.worldbank.org/wiki/Data_Security (Add information on 3-2-1 backup strategg)

**Comment by Avnish95** [comment]
https://github.com/worldbank/dime-data-handbook/blob/f8afdcbe047cc41bd29302cc098a0f7b6614ec83/chapters/2-collaboration.tex#L567

https://dimewiki.worldbank.org/wiki/Protecting_Human_Research_Subjects#European_Standards (Add info)

**Comment by Avnish95** [comment]
https://github.com/worldbank/dime-data-handbook/blob/f8afdcbe047cc41bd29302cc098a0f7b6614ec83/chapters/2-collaboration.tex#L619

https://dimewiki.worldbank.org/wiki/Informed_Consent (Add material from URL)

**Comment by Avnish95** [comment]
https://github.com/worldbank/dime-data-handbook/blob/f8afdcbe047cc41bd29302cc098a0f7b6614ec83/chapters/2-collaboration.tex#L641

https://dimewiki.worldbank.org/wiki/Research_Ethics#Confidentiality

**Comment by Avnish95** [comment]
https://github.com/worldbank/dime-data-handbook/blob/f8afdcbe047cc41bd29302cc098a0f7b6614ec83/chapters/2-collaboration.tex#L718

https://dimewiki.worldbank.org/wiki/De-identification#Anonymizing_IDs (Add information on, and link to sdcMicro)

**Comment by Avnish95** [comment]
https://github.com/worldbank/dime-data-handbook/blob/f8afdcbe047cc41bd29302cc098a0f7b6614ec83/chapters/3-measurement.tex#L738

https://dimewiki.worldbank.org/wiki/Sampling (add information about Sampling Noise)

**Comment by Avnish95** [comment]
https://github.com/worldbank/dime-data-handbook/blob/ch-3/chapters/3-measurement.tex#L747

https://dimewiki.worldbank.org/wiki/Sample_Size_and_Power_Calculations (add section on Permutation Test, link to that instead)

**Comment by Avnish95** [comment]
https://github.com/worldbank/dime-data-handbook/blob/f8afdcbe047cc41bd29302cc098a0f7b6614ec83/chapters/3-measurement.tex#L758

Can move relevant content to https://dimewiki.worldbank.org/wiki/Sample_Size_and_Power_Calculations (most of it is already there)

**Comment by Avnish95** [comment]
https://github.com/worldbank/dime-data-handbook/blob/f8afdcbe047cc41bd29302cc098a0f7b6614ec83/chapters/4-acquisition.tex#L271

https://dimewiki.worldbank.org/wiki/Questionnaire_Design#Draft_Instrument

**Comment by Avnish95** [comment]
https://github.com/worldbank/dime-data-handbook/blob/f8afdcbe047cc41bd29302cc098a0f7b6614ec83/chapters/4-acquisition.tex#L378

https://dimewiki.worldbank.org/wiki/SurveyCTO_Coding_Practices#Variable_Names (Add content from URL)

**Comment by Avnish95** [comment]
https://github.com/worldbank/dime-data-handbook/blob/f8afdcbe047cc41bd29302cc098a0f7b6614ec83/chapters/5-processing.tex#L254

https://dimewiki.worldbank.org/wiki/High_Frequency_Checks ( add information about ipacheck from URL)

**Comment by Avnish95** [comment]
https://github.com/worldbank/dime-data-handbook/blob/ch-5/chapters/5-processing.tex#L423

https://dimewiki.worldbank.org/wiki/De-identification#Anonymizing_IDs (Add information on, and link to sdcMicro)

**Comment by Avnish95** [comment]
https://github.com/worldbank/dime-data-handbook/blob/f8afdcbe047cc41bd29302cc098a0f7b6614ec83/chapters/5-processing.tex#L443

Page no longer available, need to remove this link :(

**Comment by Avnish95** [comment]
https://github.com/worldbank/dime-data-handbook/blob/f8afdcbe047cc41bd29302cc098a0f7b6614ec83/chapters/5-processing.tex#L451

https://dimewiki.worldbank.org/wiki/Personally_Identifiable_Information_(PII) (can add information and link to PII Scan by J-PAL)

**Comment by Avnish95** [comment]
https://github.com/worldbank/dime-data-handbook/blob/f8afdcbe047cc41bd29302cc098a0f7b6614ec83/chapters/6-analysis.tex#L46

Can replace by link to planned Tidy Data Wiki page

**Comment by Avnish95** [comment]
https://github.com/worldbank/dime-data-handbook/blob/ch-5/chapters/6-analysis.tex#L742

Replace URL with https://worldbank.github.io/dime-data-handbook/

**Comment by Avnish95** [comment]
https://github.com/worldbank/dime-data-handbook/blob/f8afdcbe047cc41bd29302cc098a0f7b6614ec83/chapters/7-publication.tex#L376

https://dimewiki.worldbank.org/wiki/Publishing_Data (can link to the J-PAL guide through Wiki)

**Comment by Avnish95** [comment]
https://github.com/worldbank/dime-data-handbook/blob/f8afdcbe047cc41bd29302cc098a0f7b6614ec83/chapters/7-publication.tex#L432

https://dimewiki.worldbank.org/wiki/Data_Documentation

**Comment by Avnish95** [comment]
https://github.com/worldbank/dime-data-handbook/blob/f8afdcbe047cc41bd29302cc098a0f7b6614ec83/chapters/7-publication.tex#L449

New planned page for Data Licensing Agreement

**Comment by Avnish95** [comment]
https://github.com/worldbank/dime-data-handbook/blob/f8afdcbe047cc41bd29302cc098a0f7b6614ec83/chapters/7-publication.tex#L493

https://dimewiki.worldbank.org/wiki/Pre-Registration

**Comment by bbdaniels** [comment]
Add DIME Standards links to appropriate wiki pages, such as https://github.com/worldbank/dime-standards/blob/master/dime-research-standards/pillar-4-data-security/data-security-resources/password-manager-guidelines.md to  https://dimewiki.worldbank.org/Data\_Security

**Comment by kbjarkefur** [comment]
We have agreed on those that are still there as of #522
