### ISSUE TITLE
Chapter diagrams feedback

### ISSUE THREAD

**Issue by luizaandrade** [worldbank/dime-data-handbook#461]
Diagrams are in DIME Analytics\d4di\Chapter diagrams

**Comment by kbjarkefur** [comment]
- [ ] in acquisition, call it _securely transfer data_ instead of _safely transfer data_

**Comment by bbdaniels** [comment]
My markups attached! Great work!
[Publication-bbd.pdf](https://github.com/worldbank/dime-data-handbook/files/4815546/Publication-bbd.pdf)
[Overview-bbd.pdf](https://github.com/worldbank/dime-data-handbook/files/4815547/Overview-bbd.pdf)
[Cleaning-bbd.pdf](https://github.com/worldbank/dime-data-handbook/files/4815548/Cleaning-bbd.pdf)
[Acquisition-bbd.pdf](https://github.com/worldbank/dime-data-handbook/files/4815549/Acquisition-bbd.pdf)
[Analysis-bbd.pdf](https://github.com/worldbank/dime-data-handbook/files/4815550/Analysis-bbd.pdf)

**Comment by mariaruth** [comment]
awesome @luizaandrade ! i am adding comments to the pdfs in dropbox

**Comment by bbdaniels** [comment]
Feedback on the current editions for next revision so we can merge code in now.

[Figures.BBD.pdf](https://github.com/worldbank/dime-data-handbook/files/5132463/Figures.BBD.pdf)

**Comment by kbjarkefur** [comment]
closed in #502
