### ISSUE TITLE
Ch 3 to dos

### ISSUE THREAD

**Issue by mariaruth** [worldbank/dime-data-handbook#462]
Pending items as of 22 June:

- [x] create skeleton

- [ ] add DIME examples throughout, especially to methods

- [ ] decide what content is going to be moved into an appendix / wiki, and make sure that the level of detail presented is consistent across all sections

- [ ] rewrite intro

- [ ] re-organize methods section (https://github.com/worldbank/dime-data-handbook/pull/448#discussion_r443643295)

**Comment by luizaandrade** [comment]
Close?

**Comment by mariaruth** [comment]
there are still pending tasks here, are they all addressed in other issues?

**Comment by bbdaniels** [comment]
Close, as this section no longer really exists independently
