### ISSUE TITLE
Monitoring data: treatment compliance or take-up

### ISSUE THREAD

**Issue by kbjarkefur** [worldbank/dime-data-handbook#464]
@bbdaniels suggested: maybe replace this with a discussion on treatment compliance or take-up or both? Lets discsuss.

https://github.com/worldbank/dime-data-handbook/blob/7e2e8c1af1819d5442e3b5e62f8fc87e0b987f76/chapters/sampling-randomization-power.tex#L374-L389

**Comment by luizaandrade** [comment]
Close?
