### ISSUE TITLE
Comments in #448 about data map/master data

### ISSUE THREAD

**Issue by kbjarkefur** [worldbank/dime-data-handbook#465]
https://github.com/worldbank/dime-data-handbook/blob/7e2e8c1af1819d5442e3b5e62f8fc87e0b987f76/chapters/sampling-randomization-power.tex#L73

@luizaandrade 
We should discuss this further in the meeting, but I feel there is too much emphasis on units of observation and master datasets. These are important, but I'm not sure how common it is for a project to rely so strongly on different levels of observation.

--- 

https://github.com/worldbank/dime-data-handbook/blob/7e2e8c1af1819d5442e3b5e62f8fc87e0b987f76/chapters/sampling-randomization-power.tex#L82-L86

@luizaandrade There seems to be some back-and-forth here between data map and master datasets. I think the best way to frame this is:

* the first thing you need to do is create a data map
* a key aspect of the data map is how different units of observation relate to each other
* introduce master datasets here as doing that

---

https://github.com/worldbank/dime-data-handbook/blob/7e2e8c1af1819d5442e3b5e62f8fc87e0b987f76/chapters/sampling-randomization-power.tex#L93-L97

@luizaandrade 
I don't see how this follows from what's been discussed so far. I think what this is meant to say is that sampling and treatment assignment are very significant research activities and the unit of observation at which this is done must have a master dataset.

To explain why the master dataset should be used when sampling or assigning treatment, we need some more discussion. The master dataset also comes from field data, doesn't it? And the master dataset may change with the addition of new observations during a new survey round. So we should also discuss how this affect sampling and randomization reproducibility.

--- 

https://github.com/worldbank/dime-data-handbook/blob/7e2e8c1af1819d5442e3b5e62f8fc87e0b987f76/chapters/sampling-randomization-power.tex#L112-L115

@ mariaruth 
in my experience it's also useful for the data map to link back to the research design, e.g. the variables in the primary specification. this datasets is how we'll get outcome X, control vector will come from that dataset, etc etc. that also ties into the theme of this chapter of developing the measurement framework.

---

https://github.com/worldbank/dime-data-handbook/blob/7e2e8c1af1819d5442e3b5e62f8fc87e0b987f76/chapters/sampling-randomization-power.tex#L210-L211

@luizaandrade 
what happens when the master is updated?

@mariaruth
Need to clarify language around master dataset so that it is clear that it is to serve as key or crosswalk and not to be (permanently) merged into other data sources; @luizaandrade good if you could suggest edits

---

https://github.com/worldbank/dime-data-handbook/blob/7e2e8c1af1819d5442e3b5e62f8fc87e0b987f76/chapters/sampling-randomization-power.tex#L402-L406

@luizaandrade
Add some wording about how the tracking of observations should be defined before any data collection is made, and kept the same across all round of data collection. This is a good example, but is not unique to monitoring data, and does not link to why this should be done at the data map stage, as opposed to right before monitoring.

**Comment by kbjarkefur** [comment]
@luizaandrade and @mariaruth , I think this can be closed now. all of the text that these comments refer to have been re-written and I think all your comments have been address. But I want to let you remind yourself of these comments before I close this issue after which these comments are most likely never read again.

**Comment by luizaandrade** [comment]
I think this can be closed

**Comment by mariaruth** [comment]
I think we still don't talk about linking the data map back to the research design, e.g. which datasets will be used to get which outcome vars.

**Comment by kbjarkefur** [comment]
Make sure that sentences in intro:

> As you prepare a research project for the creation or acquisition of original data, you will need to develop a structure into which that data will help you answer your research questions. This is part of what we call the measurement framework, or the system within which you can start to make sense of the data points you will collect during your project.

and:

> These three tools will help to communicate the project’s data requirements both across the team and across time. This section also discusses what specific research data you need based on your project’s research design, and how to document those data needs in the data map.

are in the actual chapter

**Comment by kbjarkefur** [comment]
@mariaruth , this is now how we tie the data map to the research design. If this is sufficient, then merge #517

#### In intro:

https://github.com/worldbank/dime-data-handbook/blob/3bd25d30443bec9c21429677c537793cbc86d915/chapters/3-measurement.tex#L5-L7

https://github.com/worldbank/dime-data-handbook/blob/3bd25d30443bec9c21429677c537793cbc86d915/chapters/3-measurement.tex#L27-L31

#### in data map section:

https://github.com/worldbank/dime-data-handbook/blob/3bd25d30443bec9c21429677c537793cbc86d915/chapters/3-measurement.tex#L109-L112
