### ISSUE TITLE
Fix file mess before merging to develop

### ISSUE THREAD

**Issue by kbjarkefur** [worldbank/dime-data-handbook#471]
For the chapters that you have been the main re-writer for, please indicate if file is to be used or not. Here and exactly here and nowhere else the place I need you to check: https://github.com/worldbank/dime-data-handbook/tree/develop-kb/chapters

Some of them I have already I have already replaced all content with "No Use" to help my merging. But I need you to confirm that I understood it correctly and that the content you expect to be in these chapters is in at least one file.

Do not worry about the file names or the manuscript file. That is easy to solve once we know we have the right content in this branch. Remember to only look here https://github.com/worldbank/dime-data-handbook/tree/develop-kb/chapters for this exercise.

You can also see the commit history for each file to make sure that you see the commits you expect to see there.

1a-reproducibility.tex
- [x] Use this file
- [ ] Do not use this file

2-collaborating.tex
- [ ] Use this file
- [x] Do not use this file

5-acquiring-data.tex
- [ ] Use this file
- [x] Do not use this file

6-analyzing-data.tex
- [ ] Use this file
- [x] Do not use this file

7-publication.tex
- [x] Use this file
- [ ] Do not use this file

abbreviations.tex
- [x] Use this file
- [ ] Do not use this file

conclusion.tex
- [x] Use this file
- [ ] Do not use this file

data-analysis.tex
- [x] Use this file
- [ ] Do not use this file

data-collection.tex
- [x] Use this file
- [ ] Do not use this file

data-processing.tex
- [x] Use this file
- [ ] Do not use this file

handling-data.tex
- [ ] Use this file
- [ ] Do not use this file

introduction.tex
- [x] Use this file
- [ ] Do not use this file

notes.tex
- [x] Use this file
- [ ] Do not use this file

planning-data-work.tex
- [x] Use this file
- [ ] Do not use this file

publication.tex
- [ ] Use this file
- [x] Do not use this file

sampling-randomization-power.tex
- [x] Use this file
- [ ] Do not use this file

Let me know if you have questions!

**Comment by kbjarkefur** [comment]
When this is done, then I will make these corrections in #460 and then merge. Then we can start doing next tasks.

**Comment by bbdaniels** [comment]
@kbjarkefur A file called `7-publication.tex` should be included and should be the version at: https://github.com/worldbank/dime-data-handbook/blob/ch7-re-write/chapters/7-publication.tex

**Comment by kbjarkefur** [comment]
@bbdaniels , I added back `7-publication` from that link in dc603948aaa6b51e9a5096e1a3d272c118c13c4b

**Comment by bbdaniels** [comment]
This is done with the last merge @kbjarkefur -- closing now, undo if this is wrong.
