### ISSUE TITLE
Intro edits

### ISSUE THREAD

**Issue by luizaandrade** [worldbank/dime-data-handbook#481]
- Edit this sentence to make it clear that we always recommend using Style guides, even if it is not for Stata, but there wasn't one for Stata before
https://github.com/worldbank/dime-data-handbook/blob/970f1f406184ef3bb2787ac375085c42623196e4/chapters/0-introduction.tex#L332

- Kris and I had to read this sentence a couple of times. Can we make it clearer?
https://github.com/worldbank/dime-data-handbook/blob/970f1f406184ef3bb2787ac375085c42623196e4/chapters/0-introduction.tex#L246

**Comment by kbjarkefur** [comment]
I think we can close

**Comment by kbjarkefur** [comment]
@maria to review intro

**Comment by kbjarkefur** [comment]
Duplicate of #424 so I will close this
