### ISSUE TITLE
Shorten DIME-standards links

### ISSUE THREAD

**Issue by kbjarkefur** [worldbank/dime-data-handbook#488]
Instead of scary links like https://github.com/worldbank/dime-standards/tree/master/dime-research-standards/pillar-4-data-security or https://github.com/worldbank/dime-standards/blob/master/dime-research-standards/pillar-4-data-security/data-security-resources/password-manager-guidelines.md in the book do either of this:

1. If it is a link to a pilar in general say: "See pilar 4 in https://github.com/worldbank/dime-standards" - (but this requires that we improve the dime-standards README)
2. If it is a link to a resource on the dime-standards repo: Create a wiki page on the topic and link to the resource from there.

Both these two options have succinct URLs that are also descriptive (at least more descriptive that an git.io or bit.ly link)

**Comment by bbdaniels** [comment]
Closing as duplicate to #499
