### ISSUE TITLE
ch 6 and 7 - include other types of publications than just academic publications

### ISSUE THREAD

**Issue by kbjarkefur** [worldbank/dime-data-handbook#491]
Make this resource more useful to a broader audience by including more non-academic types of publications.

For example, dashboards, info-graphics etc. 

Make this useful for a government officer or NGO worker that just want to create an internal report.

**Comment by bbdaniels** [comment]
I did substantial changes to Ch7 for this but tried to do it in one line for Ch6 since I think the chapter was sufficiently broadly written. @luizaandrade let me know if you think this approach for Ch6 is insufficient and I'll take a broader pass?

**Comment by luizaandrade** [comment]
This is duplicated with #500

**Comment by kbjarkefur** [comment]
The other issue had some more info, so I moved there and vote to close this one
