### ISSUE TITLE
DIME Standards: Landing readme

### ISSUE THREAD

**Issue by kbjarkefur** [worldbank/dime-data-handbook#499]
Make the landing page README a better place to land on: https://github.com/worldbank/dime-standards. Call the five pillars Pillar 1, Pillar 2 etc in the README.

Then in the book, instead of linking to individual .md documents with super long URLs, do:

```
\sidenote{See pillar 4 in the DIME Research Standards \url{https://github.com/worldbank/dime-standards}}
```
or

```
\sidenote{See resources related to pillar 4 in the DIME Research Standards \url{https://github.com/worldbank/dime-standards}}
```

**Comment by bbdaniels** [comment]
I shortened all the URLs on this but they should be reviewed to reference the right pillars in text.

**Comment by mariaruth** [comment]
@kbjarkefur @luizaandrade @bbdaniels the readme is updated. However, I still wonder whether it might be better to include all of the content in the research standards readme on the main readme. we would need to also add some more to the coding standards on that readme so it doesn't look totally imbalanced. but i think that would help reduce confusion a lot.

**Comment by kbjarkefur** [comment]
Done in : https://github.com/worldbank/dime-standards/pull/19
