### ISSUE TITLE
include non-academic publications

### ISSUE THREAD

**Issue by kbjarkefur** [worldbank/dime-data-handbook#500]
This book is very focused on academic publications. That is not bad, but it miss the point of all the other ways of disseminating insights based on development data that the audience of this book will be interested in.

We do not have a ton of material on this, so we cannot add that much, but lets see what we can add

---- 
originally posted in #487 liek this:

* Very focused on academic publications, but this should include dashboards, infographics etc and other types of research products useful in the context of development.
  * Add paragraph to alternative types of output, not just academic publications. Not go in to details as we do not have much resources, just point to good DIME examples. Say that this is a good way to disseminate development result to non academic audience

**Comment by kbjarkefur** [comment]
From (duplicate) #491 :

KB:
> Make this resource more useful to a broader audience by including more non-academic types of publications.
> For example, dashboards, info-graphics etc.
> Make this useful for a government officer or NGO worker that just want to create an internal report.

and 

BBD:
> I did substantial changes to Ch7 for this but tried to do it in one line for Ch6 since I think the chapter was sufficiently broadly written. @luizaandrade let me know if you think this approach for Ch6 is insufficient and I'll take a broader pass?

**Comment by luizaandrade** [comment]
Ben had already solved it in #491
