### ISSUE TITLE
Revise acknowledgements

### ISSUE THREAD

**Issue by bbdaniels** [worldbank/dime-data-handbook#501]
Need to name specific people, funders, etc, and include WB disclaimer language if that is not already there

**Comment by luizaandrade** [comment]
## People
- Roshni
- Radhika
- Yifan
- Maria Arnal
- Thomas
- Ravi
- Nausheen
- Leo
- Aram
- Caio
- Stephanie
- Michael
- Francesco
- Dan
- Cami
- Steven

**Comment by bbdaniels** [comment]
disclaimer language to add:

The findings, interpretations, and conclusions expressed here are those of the authors and do not necessarily represent the views of the World Bank, its executive directors, or the governments they represent.

**Comment by bbdaniels** [comment]
Arianna Legovini, for her leadership of the DIME team and unending support. Florence Kondylis, for her leadership in founding and growing the DIME Analytics team. The following members of the DIME Analytics team for their contributions to the ideas in this book and their help organizing them here: [Roshi, etc]. The many people who read and offered feedback as we developed the manuscript: [alphabetical]. And, of course, all the members of DIME and its teams across all the years.

**Comment by luizaandrade** [comment]
Arianna Legovini, for her leadership of the DIME team and unending support, **as well as detailed revision of this book**. Florence Kondylis, for her leadership in founding and growing the DIME Analytics team. The following members of the DIME Analytics team for their contributions to the ideas in this book and their help organizing them here: [Roshni, etc]. The many people who read and offered feedback as we developed the manuscript: [alphabetical]. And, of course, all the members of DIME and its teams across all the years.

**Comment by bbdaniels** [comment]
[ie-in-practice (frontmatter).pdf](https://github.com/worldbank/dime-data-handbook/files/5233381/ie-in-practice.frontmatter.pdf)

**Comment by kbjarkefur** [comment]
Close?
