### ISSUE TITLE
Chapter 2: Move "Organizing code and data" section before "Preparing a collaborative work environment"

### ISSUE THREAD

**Issue by bbdaniels** [worldbank/dime-data-handbook#504]
I think these two sections read out of order and should be reversed. This is @kbjarkefur section but it I don't think any rewriting is necessary to do this.

**Comment by kbjarkefur** [comment]
@bbdaniels , i definitely see what you are saying, but i do not think the correction is as simple as changing order.

If we want to fix this we need more work on this.

**Comment by kbjarkefur** [comment]
I will list what each paragraph is about in an excel sheet, and then see how this can be restructured

**Comment by kbjarkefur** [comment]
@bbdaniels and I discussed, and this is too much work in relation to the marginal gain at this point. Time is better spent on wiki articles now, and then we can see what the reviewers say
