### ISSUE TITLE
Wiki page for data retention / destruction. 

### ISSUE THREAD

**Issue by bbdaniels** [worldbank/dime-data-handbook#512]
We should have a wiki page for data retention / destruction. @Avnish95 some resources: 
https://kb.mit.edu/confluence/display/istcontrib/Removing+Sensitive+Data --> how to actually remove data
https://studentprivacy.ed.gov/resources/best-practices-data-destruction 
https://www.povertyactionlab.org/resource/data-security-procedures-researchers --> JPAL's protocols

_Originally posted by @mariaruth in https://github.com/worldbank/dime-data-handbook/pull/511#discussion_r488141287_

**Comment by bbdaniels** [comment]
I suggest this to go on the Data Storage wiki page but happy for a new one if you think needed. Not doing this in the outdo PR though

**Comment by mariaruth** [comment]
i didn't realize we had a data storage page! i think that's fine

**Comment by kbjarkefur** [comment]
Included here: https://dimewiki.worldbank.org/Data_Storage#Data_retention
