### ISSUE TITLE
Content to move to wiki

### ISSUE THREAD

**Issue by mariaruth** [worldbank/dime-data-handbook#524]
### LaTeX
To create a {\LaTeX} document, you will typically start a new directory for each research output to hold the files and outputs for that document only. For a single output, we recommend putting the core document files (such as \texttt{main.tex} and \texttt{bibliography.bib}) in the top-level folder, and then have subfolders for figures, tables, and other inputs. Your analysis scripts should be set up such that it is easy to output files to this location by adjusting paths in the master script. Above all, keep your workflow as simple as possible.

BibTeX is so widely used that it is natively integrated in Google Scholar. To obtain a reference in the \texttt{.bib} format for any paper you find, click ``BibTeX'' at the bottom of the Cite window (below the preformatted options). Then, copy the code directly into your \texttt{.bib} file. They will look like the following:

\codeexample{sample.bib}{./code/sample.bib}

\noindent BibTeX citations are then used as follows:

\codeexample{citation.tex}{./code/citation.tex}

With this tool, you can ensure that references are handled in a format you can manage and control.\cite{flom2005latex}
By changing some settings in the document itself, you can change the style of inline citations and bibliographical references.
You can, for example, use superscripts or author names inline, and order the bibiliography either by order of appearance or alphabetically. All the formatting and numbering will be handled automatically. You can also choose to display only the references which are cited in the text, or to include every reference in the \texttt{.bib} file.

### data viz
Rather, here are a few resources we have found useful. The Tapestry conference focuses on ``storytelling with data''.\sidenote{
	\url{http://www.tapestryconference.com}} \textit{Fundamentals of Data Visualization} provides extensive details on practical application;\sidenote{ \url{https://serialmentor.com/dataviz}} as does \textit{Data Visualization: A Practical Introduction}.\sidenote{\url{http://socvis.co}} Graphics tools in Stata are highly customizable. There is a fair amount of learning curve associated with extremely-fine-grained adjustment, but it is well worth reviewing the graphics manual.\sidenote{\url{ 		https://www.stata.com/manuals/g.pdf}} For an easier way around it, you can use built-in and user-written graph schemes.\sidenote{ \url{https://dimewiki.worldbank.org/Data_visualization}} If you are an R user, the \textit{R Graphics Cookbook} is a great resource for the its popular visualization package \texttt{ggplot}\sidenote{\url{https://r-graphics.org} and
	\url{https://ggplot2.tidyverse.org}}, as is the \textit{The R Graph Gallery}: \url{https://www.r-graph-gallery.com}} 
But there are a variety of other visualization packages, such as \texttt{highcharter}, \texttt{r2d3}, \texttt{leaflet}, and \texttt{plotly} to name a few.\sidenote{ \url{http://jkunst.com/highcharter}, 	\url{https://rstudio.github.io/r2d3}, \url{https://rstudio.github.io/leaflet} and \url{https://plot.ly/r}}.
We have no intention of creating an exhaustive list, but these are good places to start.\sidenote{  \url{https://dimewiki.worldbank.org/Checklist:\_Reviewing\_Graphs}}

**Comment by Avnish95** [comment]
@bbdaniels @mariaruth We can create this as a new page on LaTeX, and then link to Coding Practices.
