### ISSUE TITLE
Ch. 6

### ISSUE THREAD

**Issue by MichaelBeeli** [worldbank/dime-data-handbook#558]
- [x] DIME Wiki Links missing descriptions
    (footnote #) (link) (pg #) 
   - [ ]  (27) https://dimewiki.worldbank.org/wiki/Ieddtab (pg. 109)
   - [ ] (28) https://dimewiki.worldbank.org/Checklist:_Submit_Table (pg. 109)
   - [ ] (26) https://dimewiki.worldbank.org/wiki/Iebaltab (pg. 109)
   - [ ] (18) https://dimewiki.worldbank.org/Data_visualization (pg. 106)
   - [ ] (8) https://dimewiki.worldbank.org/Variable_Construction%23Dealing_with_outliers (pg. 102) 
   - [ ] (7) https://dimewiki.worldbank.org/wiki/Data_Linkage_Table (pg. 101)
   - [ ] (6) https://dimewiki.worldbank.org/Data_Flow_Charts (pg. 101)
   - [ ] (5) https://dimewiki.worldbank.org/wiki/Data_Integration#Planning_Data_Integration (pg. 101)
   - [ ] (4) https://dimewiki.worldbank.org/Unit_of_Observation (pg. 99)
- [x] Links leading to broken/stub pages 
   - [x] (5) https://dimewiki.worldbank.org/wiki/Data_Integration#Planning_Data_Integration (pg. 101)
   - [x] (8) https://dimewiki.worldbank.org/Variable_Construction%23Dealing_with_outliers (pg. 102)
- [x] Links that do not work 
  - [x] (18) https://dimewiki.worldbank.org/Data_visualization (pg. 106)
  - [x] (4) https://dimewiki.worldbank.org/Unit_of_Observation (pg. 99)
- [x] Footnotes that do not redirect to bibliography citation
  - [ ] (1) Wickham and Grolemund (2017) 2 (pg. 99)
  - [ ] (3) See Adjognon et al. (2019) for an example. (pg. 99)
  - [ ] (15) Healy (2018); Wilke (2019) (pg. 106)
  - [ ] (21) Jann (2005), Jann (2007) (pg. 108)
  - [ ] (22) Wada (2014) (pg. 108)
  - [ ] (23) Daniels (2019) (pg. 108)
  - [ ] (24) Hlavac (2015) (pg, 108)
  - [ ] (25) Wickham (2016) (pg 108)
  - [ ] (33) Rodriguez (2017) (pg. 110)
  - [ ] (34) Haghish (2016) (pg. 110)
  - [ ]  (35) Jann (2017) (pg. 110)
  - [ ]  (36) Jann (2016) (pg. 110) 
- [x] Other issues
  - [x] "Our team created iefieldkit’s iecodebook append subcommand" (pg. 103) — Has no footnote 
  - [x] "keeping the original variable in the dataset will allow you to test how much it affects your outputs." (pg. 102-103) — Imprecise wording 
  - [x] "If your are subsetting your data by keeping only matched observations" (pg. 101) — Typo, should be "if **you** are" 
  - [x] "To effectively do this in a team environment, data, code and outputs must be well-organized, with a clear system for version control, analysis scripts that can be run by all team members, and creation of research outputs fully automated." (pg. 99) — Suggest: "the creation of research outputs **must** be fully automated

**Comment by luizaandrade** [comment]
thank you, @MichaelBeeli !!
