### ISSUE TITLE
Chap6

### ISSUE THREAD

**Issue by disovankiriboung** [worldbank/dime-data-handbook#562]
- There were some keywords that are bold; are there any rules for bolding the words?
- Page 114, section "creating analysis variable": the word "0" does not look like zero, and the font for "true" and "false", "gender" is different
from the main text
- Footnote 8 on outliner, should be added next to the word 'outliner'?
- Page 118, just above the section "visualization Data", the book mention about spatial-diff-in-diff.do, matching-villages.R, and summary-statistics.py, but I do not where they are, should there be a footnote to where they are?
- Page 120 : Typo error: section "Managing outputs", paragraph 1 - **They they** use more space....

**Comment by luizaandrade** [comment]
thank you, kiri!
