### ISSUE TITLE
Chap7

### ISSUE THREAD

**Issue by disovankiriboung** [worldbank/dime-data-handbook#563]
- [x] Footnote 2 - link is not working
- [x] page 129, next to foot note 5, grammar mistake: ....**any journal** (should be plural)

**Comment by MichaelBeeli** [comment]
- Footnotes 15, 19, 23, 27, 28 missing descriptiions
- Page 118 "In some cases, it may be possible to release the dataset but embargoing specific variables that are required for the analysis but cannot be released publicly" seems to be missing a word 
- Footnote 21, no link

**Comment by luizaandrade** [comment]
- Footnote 2 seems to be a problem with LaTeX, not showing on current version of html or word

**Comment by luizaandrade** [comment]
Thanks, guys!
