### ISSUE TITLE
Typos in invalid links

### ISSUE THREAD

**Issue by yukinko-iwasaki** [worldbank/dime-data-handbook#586]
I found some minor issues with links while reading the handbook.

1. A space in the URL address makes the link invalid
https://github.com/worldbank/dime-data-handbook/blob/main/chapters/1-reproducibility.Rmd#L527C64-L527C64

2. Image link is not valid
https://github.com/worldbank/dime-data-handbook/blob/3988e0d1646db57cb9b61b5f8a74114ce3ac212c/chapters/5-processing.Rmd#L941C28-L941C28
The `png` might have to be in upper letters.

<img width="747" alt="Screenshot 2023-09-21 at 4 22 25 PM" src="https://github.com/worldbank/dime-data-handbook/assets/18432543/cc80a77c-9560-43c8-9fb6-b51af4e12d61">

3. A typo?  ateam => a team
https://github.com/worldbank/dime-data-handbook/blob/3988e0d1646db57cb9b61b5f8a74114ce3ac212c/chapters/6-analysis.Rmd#L5

Note: 
I am not sure how the pdf file corresponds to the GitHub version of the handbook. However, it is possible that the indentation in the pdf could be doing something unintended for the white spaces in the GitHub version of the handbook.

**Comment by kbjarkefur** [comment]
Thanks for reporting on this! I have fixed all these issues here: 2aec05473350540ebc5dbdd8a0bbda54db7f8e93

The spaces are probably related to PDF format as you say. But I think it comes from the PDF that we worked on together with the editor when the book was being published. Then the last version of that PDF was copy-pasted back to the Rmd files that is used on the bookdown site you are looking at. The spaces was then corrected by hand, but we must have missed the section you point to. Great to have this fixed. Thanks!

Agreed that all file extensions should be lower case. The tricky thing is that windows computers do not care, so when rendered locally this might work, but the linux server (most likely linux) running this site is not case-indifferent.

Thanks again for reporting this!
