### ISSUE TITLE
List of most common Stata command

### ISSUE THREAD

**Issue by kbjarkefur** [worldbank/dime-data-handbook#74]
I had a question during Stata track 1 during the FC training that more or less asked: "_Is there a list of all the commands in Stata so I can learn them?_". It is obviously not the best approach but after some discussion in the class we thought it would be good to have a list of the most commonly used commands.

I think we can have a top 20 list. But then have a 21-50 list, and maybe also a 51-100 list. This list would have a one sentence description of what the command is used for. Then the top 20 could maybe go in the book, but the other list would go to the Wiki. 

And I think we should not include analysis, cause people tend to learn them anyways. Just data management, data cleaning, and data exploration.

I think this still needs a lot of fine tuning on how we would do this, but I think it would be very helpful.

**Comment by luizaandrade** [comment]
This sounds interesting. Some of the common commands for data management and cleaning are not super intuitive and can cause errors (I'm thinking of `merge`, `reshape`, `collapse`, but also `gen` vs `egen`). I think we could include a list, and possibly a Wiki article for these.

If we're doing an "RA retreat", I think this would be a good space both to discuss what should be in this list, but also to discuss best practices for them and maybe (ask senior RAs to) develop a quick presentation.

**Comment by bbdaniels** [comment]
These three I think are OK:

https://www.stata.com/manuals13/u27.pdf

https://library.duke.edu/data/sites/default/files/datagis/store/quick_reference.docx

https://scholar.harvard.edu/files/mcgovern/files/practical_introduction_to_stata.pdf

**Comment by bbdaniels** [comment]
<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Stata users will get a kick out of this:<br><br>Stata v1.0 (released January 1985) only had these 44 commands.<br><br>Source: <a href="https://t.co/a4gyiPu72n">https://t.co/a4gyiPu72n</a> <a href="https://t.co/U189Y3pL9Y">pic.twitter.com/U189Y3pL9Y</a></p>&mdash; John B. Holbein (@JohnHolbein1) <a href="https://twitter.com/JohnHolbein1/status/1156224843991453702?ref_src=twsrc%5Etfw">July 30, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mariaruth** [comment]
@kbjarkefur - should this go in the Stata appendix?

**Comment by kbjarkefur** [comment]
yes, I'd say so. The top 20 in the Stata appendix and then links to the wiki.

**Comment by bbdaniels** [comment]
Added two resource links (2adf384887cf93bb2fa2855c7634acf50c94e59e). Anything else to final review.
