### ISSUE TITLE
Integration of MSIE or Lab materials

### ISSUE THREAD

**Issue by bbdaniels** [worldbank/dime-data-handbook#96]
Hi all,

Do you think we should integrate the MSIE materials or the Stata/R lab sessions? These are now all living at https://osf.io/79z5h/ from last year.

**Comment by mariaruth** [comment]
Yes! I think adding practical exercises would significantly increase the value of the book. A lot of work has gone into MSIE materials over the years, and they've already gone through some review with multiple implementation. Also, if we include the R materials, we can mention that in the intro (when we explain that by default we refer to stata code in the book)

**Comment by luizaandrade** [comment]
Should we add the exercises to the printed book, or as an online appendix? I agree that exercises would increase the value of the book. However, I am not sure how to do that, since oftentimes the exercises are about technical content that is not covered in the book.

**Comment by bbdaniels** [comment]
We could link from appendix?

**Comment by mariaruth** [comment]
Shall we add a second appendix for this? We could have a short blurb for the class (basically what's on the website) and then links to the different lab sessions and materials?

**Comment by kbjarkefur** [comment]
Make appendix where we list link and blurbs

**Comment by luizaandrade** [comment]
this is done in #410
